<?xml version="1.0" encoding="utf-8"?>
<feature>
	<version>1</version>
	<uuid>c5f1f190-8eef-4139-8d6a-9f2643f61ebd</uuid>
	<name>External Inlet Fan 1</name>
	<type>43</type>
	<res_file_key>1aa4e56c-6f20-4ed5-9df0-6098a8945787</res_file_key>
	<cs_name/>
	<cs_uuid>f92f02ce-8dd9-49f9-868e-ad4cf185242b</cs_uuid>
	<x_form>
		<global>false</global>
		<origin>
			<item>0.08571769551206386</item>
			<item>-0.094559916449439924</item>
			<item>0.063226364862251375</item>
		</origin>
		<translate>
			<item>0.0092750416139890293</item>
			<item>0.9999569858764219</item>
			<item>0</item>
			<item>-0.011512003758099361</item>
			<item>0.00010677890691786738</item>
			<item>0.99993372898794564</item>
			<item>0.99989071771495719</item>
			<item>-0.0092744269475944253</item>
			<item>0.011512498958152239</item>
		</translate>
	</x_form>
	<display_bl>false</display_bl>
	<interpolate>true</interpolate>
	<use_cad_geom>false</use_cad_geom>
	<moving_reference>true</moving_reference>
	<moving_display>true</moving_display>
	<full_task>false</full_task>
	<use_in_BRP>false</use_in_BRP>
	<transparency>0</transparency>
	<use_all_faces>false</use_all_faces>
	<geom_ref>
		<item>
			<uuid>f92f02ce-8dd9-49f9-868e-ad4cf185242b</uuid>
			<name/>
			<type>-1</type>
			<id1>0</id1>
			<id2>0</id2>
			<update_stamp>0</update_stamp>
			<group>-1</group>
			<geom_stamp_uuid/>
			<origin>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</origin>
			<normal>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</normal>
			<vector>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</vector>
			<pos>0</pos>
			<flip>1</flip>
			<min>0</min>
			<max>0</max>
			<curve_data>
				<start>0</start>
				<end>0</end>
				<length>0</length>
				<data/>
			</curve_data>
			<path>
				<path_elems/>
			</path>
		</item>
	</geom_ref>
	<parameter>
		<item>
			<type>1</type>
			<dependency_type>0</dependency_type>
			<value>293.19999999999999</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>5</type>
			<dependency_type>0</dependency_type>
			<value>101325</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>118</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>119</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>120</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>121</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>122</type>
			<dependency_type>0</dependency_type>
			<value>1</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>123</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>124</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>125</type>
			<dependency_type>0</dependency_type>
			<value>1</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>126</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>127</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>130</type>
			<dependency_type>0</dependency_type>
			<value>0.75</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>131</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>201</type>
			<dependency_type>0</dependency_type>
			<value>0.10000000000000001</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>202</type>
			<dependency_type>0</dependency_type>
			<value>0.00062114786119496078</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>203</type>
			<dependency_type>0</dependency_type>
			<value>1</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>204</type>
			<dependency_type>0</dependency_type>
			<value>1</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>999</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1001</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1002</type>
			<dependency_type>0</dependency_type>
			<value>200</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1012</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1013</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1018</type>
			<dependency_type>0</dependency_type>
			<value>1</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1019</type>
			<dependency_type>0</dependency_type>
			<value>1</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1037</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1039</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1106</type>
			<dependency_type>0</dependency_type>
			<value>101325</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1107</type>
			<dependency_type>0</dependency_type>
			<value>293.19999999999999</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1108</type>
			<dependency_type>0</dependency_type>
			<value>50</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1115</type>
			<dependency_type>0</dependency_type>
			<value>1</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1132</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1135</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1136</type>
			<dependency_type>0</dependency_type>
			<value>1</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1228</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1229</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1322</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1429</type>
			<dependency_type>0</dependency_type>
			<value>1</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
		<item>
			<type>1478</type>
			<dependency_type>0</dependency_type>
			<value>0</value>
			<formula/>
			<x/>
			<y/>
			<types/>
			<values/>
			<periodic>false</periodic>
			<chart>false</chart>
			<scale>false</scale>
			<SubstUUID/>
			<unit>42</unit>
			<goal_uuid/>
			<vis_parameter/>
		</item>
	</parameter>
	<fan_type>0</fan_type>
</feature>
